package com.rgu5android.retrofit.greendao.github.api.demo.greenDAO;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig githubGDDaoConfig;

    private final GithubGDDao githubGDDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        githubGDDaoConfig = daoConfigMap.get(GithubGDDao.class).clone();
        githubGDDaoConfig.initIdentityScope(type);

        githubGDDao = new GithubGDDao(githubGDDaoConfig, this);

        registerDao(GithubGD.class, githubGDDao);
    }
    
    public void clear() {
        githubGDDaoConfig.getIdentityScope().clear();
    }

    public GithubGDDao getGithubGDDao() {
        return githubGDDao;
    }

}
